### ISSUE TITLE
Install fail

### ISSUE THREAD

**Issue by richburdon** [pazdera/gitwalk#7]
```
▶ npm install -g gitwalk
npm WARN deprecated github@0.2.4: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
/usr/local/bin/gitwalk -> /usr/local/lib/node_modules/gitwalk/out/bin/gitwalk.js

> nodegit@0.5.0 install /usr/local/lib/node_modules/gitwalk/node_modules/nodegit
> node lifecycleScripts/install

/usr/local/lib/node_modules/gitwalk/node_modules/promisify-node/utils/args.js:9
  var args = func.toString().match(/function\s.*?\(([^)]*)\)/)[1];
                                                              ^

TypeError: Cannot read property '1' of null
    at module.exports (/usr/local/lib/node_modules/gitwalk/node_modules/promisify-node/utils/args.js:9:63)
    at /usr/local/lib/node_modules/gitwalk/node_modules/promisify-node/index.js:79:29
    at Array.filter (<anonymous>)
    at processExports (/usr/local/lib/node_modules/gitwalk/node_modules/promisify-node/index.js:60:6)
    at module.exports (/usr/local/lib/node_modules/gitwalk/node_modules/promisify-node/index.js:112:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/gitwalk/node_modules/nodegit/generate/scripts/generateNativeCode.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
```

**Comment by carsonoid** [comment]
+1

**Comment by aberberich** [comment]
seeing this same issue sadly.

**Comment by dcunited001** [comment]
+1

**Comment by dcunited001** [comment]
i looked around and this project seems to have the best approach to handling what i want (i.e. downloading/managing dozens/hundreds of repositories). i kinda wish it there was a git extension that had the same JSON interface or something. 

@richburdon @carsonoid @aberberich there are two forks with more recent commits.

both @athombv and @InsiderIn have forks with commit, but i'm running into install issues there as well. i don't have a ton of recent experience with npm and i think there's some issue with bad state on my end.

hopefully @pazdera can help us figure it out.

**Comment by dcunited001** [comment]
here are the projects that i checked out:

### TODO standardize a format for listing repos to clone for a language like clojure/julia/etc or use the following (preferred at top) 

-   [pazdera/gitwalk](https://github.com/pazdera/gitwalk) (popular,
    allows groups defined via JSON, best so far)
-   [mixu/gr](https://github.com/mixu/gr) (another promising bulk
    management tool)
    -   similar to my old gitar scripts
    -   auto-discover local git repos, attach tags and manage as lists
-   [asottile/all-repos](https://github.com/asottile/all-repos)
    (interesting)
-   [naddeoa/git-bulk](https://github.com/naddeoa/git-bulk) (also
    probably helpful)
-   [fabiospampinato/autogit](https://github.com/fabiospampinato/autogit)
    (most popular, but aimed towards personal/org repo management)
-   [scivision/pygit-bulk](https://github.com/scivision/pygit-bulk) and
    [GitMC](https://pypi.org/project/gitutils/)
-   [Bulk backup/clone of Git Repos From A
    List](https://gist.github.com/Lukas238/8d9abbeabfcd7225e3a254d40eb0c080)
-   [RepoSweeper](https://github.com/taylorjayoung/RepoSweeper) (for
    deleting/managing Github repos)
